### PR TITLE
Upgrade gradle, support lib, move common versions to root

### PR DESCRIPTION
**Pull request by jonathan-caryl**
Defining common version numbers in the root project makes it easier to
keep everything in sync when we upgrade things.

### CODE REVIEW

**Comment by egor-n** [comment]
You have to update the `build-tools` version in the [`.travis.yml`](https://github.com/material-motion/reactive-motion-android/blob/develop/.travis.yml#L13) file as well.

**Comment by jonathan-caryl** [comment]
@egor-n done

**Review by ghost — APPROVED** [review]

**Review by pingpongboss — APPROVED** [review]
Incredibly helpful, thanks.

**Comment by pingpongboss** [comment]
Made the same changes to our scaffolding project http://codereview.cc/D2986

**Comment by pingpongboss** [comment]
The updated build-tools-25.0.2 has started causing CircleCI to fail. https://circleci.com/gh/material-motion/material-motion-android/97

```
Warning: License for package Android SDK Build-Tools 25.0.2 not accepted.
java.lang.RuntimeException: You have not accepted the license agreements of the following SDK components:
[Android SDK Build-Tools 25.0.2].
```

Seems to be an issue on the circleci side.

**Pull request merged**
